name: Build
on:
  push:
  schedule:
    - cron:  '0 1 * * 0'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.4'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - uses: testspace-com/setup-testspace@v1
        with:
          domain: samples
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install
        run: |
          gem uninstall bundler -x
          gem install bundler -v '~>1.7' # https://github.com/actions/virtual-environments/issues/232
          bundle install --deployment --retry=3 --jobs=4
          RAILS_ENV=test bundle exec rake db:migrate
      - name: Analyze
        run: |
          bundle exec rubocop --format emacs --out reports/rubocop.txt || true
          bundle exec brakeman -o reports/brakeman.json
          bundle exec brakeman_translate_checkstyle_format translate --file="reports/brakeman.json" > reports/brakeman_checkstyle.xml
          bundle exec scss-lint --no-color --format=Stats --format=Default --out=reports/scss-lint.txt  app/assets/stylesheets/ || true
      - name: Test
        run: |
          CI_REPORTS=reports/test bundle exec rake minitest test
      - name: Push
        run: |
          testspace @.testspace.txt
        if: always()
